//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2011, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 1K program for KCPSM6 in a Spartan-6 device using a 
// RAMB18WER primitive.
//
// Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
//       expansion with minimum changes being required to the hardware description. 
//       Only the lower 10-bits of the address are actually used for the 1K address range
//       000 to 3FF hex.  
//
// Program defined by 'C:\PSU_Projects\ECE540_Fall12\project2b_nexys3\BotSim31\firmware\bot31_pgm.psm'.
//
// Generated by KCPSM6 Assembler: 26 Oct 2012 - 09:59:16. 
//
//
module bot31_pgm (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire [35:0] data_in_a;
wire [35:0] data_out_a;
wire [35:0] data_out_b;
wire [13:0] address_b;
wire [35:0] data_in_b;
wire        enable_b;
wire        clk_b;
wire [3:0]  we_b;
//
assign address_a = {address[9:0], 4'b0000};
assign instruction = {data_out_a[33:32], data_out_a[15:0]};
assign data_in_a = {34'b0000000000000000000000000000000000, address[11:10]};
//
assign address_b = 14'b00000000000000;
assign data_in_b = {2'h0,  data_out_b[33:32], 16'b0000000000000000, data_out_b[15:0]};
assign enable_b = 1'b0;
assign we_b = 4'h0;
assign clk_b = 1'b0;
//
//
// 
RAMB16BWER # ( .DATA_WIDTH_A        (18),
               .DOA_REG             (0),
               .EN_RSTRAM_A         ("FALSE"),
               .INIT_A              (32'h000000000),
               .RST_PRIORITY_A      ("CE"),
               .SRVAL_A             (32'h000000000),
               .WRITE_MODE_A        ("WRITE_FIRST"),
               .DATA_WIDTH_B        (18),
               .DOB_REG             (0),
               .EN_RSTRAM_B         ("FALSE"),
               .INIT_B              (32'h000000000),
               .RST_PRIORITY_B      ("CE"),
               .SRVAL_B             (32'h000000000),
               .WRITE_MODE_B        ("WRITE_FIRST"),
               .RSTTYPE             ("SYNC"),
               .INIT_FILE           ("NONE"),
               .SIM_COLLISION_CHECK ("ALL"),
               .SIM_DEVICE          ("SPARTAN6"),
               .INIT_00             (256'h0E00006301B59000019C9007003501AF00261C401D401E001F0200B40068004A),
               .INIT_01             (256'h00D602E001F00F00008602E001F02024E019C800D031E019C900B03000260035),
               .INIT_02             (256'hDA03DB04DC02DD010A0001930B00010802C001D0200A01E6180019000C100D00),
               .INIT_03             (256'hE045410EA0200200400E00105000D00DD00DD806D9055000D00ED00ED00CD00C),
               .INIT_04             (256'hE10011001001E100110010205000A02002105000300F5000400E400E400E400E),
               .INIT_05             (256'h1001E10011D81001E10011EE1001E10011CC1001E10011CE1001E10011CE1001),
               .INIT_06             (256'h11311001E10011201001E100111710005000003A1220310F01005000E100114F),
               .INIT_07             (256'hE10011061001E10011751001E10011641001E10011531001E10011421001E100),
               .INIT_08             (256'h20B300406090D50420B30040608CD500052004105000003A1200013041065000),
               .INIT_09             (256'h010000811300014060A3D50D20B3008113000140609AD50C20B300406094D508),
               .INIT_0A             (256'h1301010000811301014060B2D50F20B300811301014060A9D50E20B300811300),
               .INIT_0B             (256'hE10011111001E10011101001E100111F1001E100110F10105000004020B30081),
               .INIT_0C             (256'h0100004712105000E10011FF1001E10011F01001E10011F11001E10011011001),
               .INIT_0D             (256'h960160E1D00F60E8D40400CD07C006D0051004205000400E400E400E400E310F),
               .INIT_0E             (256'hD10F860020EF160160EED00F60F5D40820F8071020F8970160E6D10F060020E2),
               .INIT_0F             (256'h500001C000D06100D00201030270016050000170006020F8871020F8170160F3),
               .INIT_10             (256'h92019101611ADF000700010302C001D05000900A0000D209D108500001700060),
               .INIT_11             (256'h04000103920211016128DF015000017E06000103110105000103110104000103),
               .INIT_12             (256'h0103120104000103920111016136DF025000017E060001031101050001031201),
               .INIT_13             (256'h120105000103910104000103120111026144DF035000017E0600010312010500),
               .INIT_14             (256'h06000103910105000103910104000103120111016152DF045000017E06000103),
               .INIT_15             (256'h5000017E06000103920105000103920104000103120291016160DF055000017E),
               .INIT_16             (256'h617CDF075000017E0600010392010500010392010400010312019101616EDF06),
               .INIT_17             (256'h40060070500010FF5000017E0600010392010500010311010400010392019102),
               .INIT_18             (256'hD6025010618FD4025018618CD50230F86189D701500740064006400640064006),
               .INIT_19             (256'hF1321101F133110050004010310701F0400640064006400600E0500050086192),
               .INIT_1A             (256'h19005000F131F130311F0100F1321107F1331101D000400EF1311105F1301105),
               .INIT_1B             (256'h4008420E4008410E420E420E420E420E0200310F010050000A0001931B001800),
               .INIT_1C             (256'hE1D1C21021D3D200504008100120E1CAC12021CCD10022302130B332400E400E),
               .INIT_1D             (256'h61DD910101D81128500061D9900110185000400E400E400E400E508009200210),
               .INIT_1E             (256'h500061EC930101E11364500061E7930101E11332500061E2920101DC12195000),
               .INIT_1F             (256'h0000500061FB93010330130A500061F6940101F01405500061F1930101E113C8),
               .INIT_20             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_21             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_22             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_23             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_24             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_25             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_26             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_27             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_28             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_29             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_2F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_30             (256'hD90598049902D00CD00CDC02DD014C060CD01D01D004900018FF19FF1C001D00),
               .INIT_31             (256'h0000000000000000000000000000000000002304D00ED00E01F0D00DD00DD806),
               .INIT_32             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_33             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_34             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_35             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_36             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_37             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_38             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_39             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3A             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3B             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3C             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3D             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3E             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INIT_3F             (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_00            (256'h861861861860A0286186186186086255D14AAAAAAA220A008082D74A288A802A),
               .INITP_01            (256'h8360826759DD99D677600954228618618618608A0836836820DA0D8D8D8D0A16),
               .INITP_02            (256'h48A24925DA24925DA24925DA24925DA24925DA24925DA24925DA24925D2082A0),
               .INITP_03            (256'h2D0B62D8B62D8B62D8B49544DD137405555502202A088D88888055234D34D155),
               .INITP_04            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_05            (256'h0000000000000000000000000000000000000000000000000000000000000000),
               .INITP_06            (256'h00000000000000000000000000000000000000000000000000002AAA96A91800),
               .INITP_07            (256'h0000000000000000000000000000000000000000000000000000000000000000))
   kcpsm6_rom( .ADDRA               (address_a),
               .ENA                 (enable),
               .CLKA                (clk),
               .DOA                 (data_out_a[31:0]),
               .DOPA                (data_out_a[35:32]), 
               .DIA                 (data_in_a[31:0]),
               .DIPA                (data_in_a[35:32]), 
               .WEA                 (4'h0),
               .REGCEA              (1'b0),
               .RSTA                (1'b0),
               .ADDRB               (address_b),
               .ENB                 (enable_b),
               .CLKB                (clk_b),
               .DOB                 (data_out_b[31:0]),
               .DOPB                (data_out_b[35:32]), 
               .DIB                 (data_in_b[31:0]),
               .DIPB                (data_in_b[35:32]), 
               .WEB                 (we_b),
               .REGCEB              (1'b0),
               .RSTB                (1'b0));
//
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE bot31_pgm.v
//
////////////////////////////////////////////////////////////////////////////////////
