# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ryanp/Documents/GitHub/Nexys-A7-Sidescroller-Game/fpga_code/src/liteDRAM.xdc

# XDC: C:/Users/ryanp/Documents/GitHub/Nexys-A7-Sidescroller-Game/fpga_code/src/rvfpga.xdc

# IP: ip/rojobot31_0/rojobot31_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rojobot31_0 || ORIG_REF_NAME==rojobot31_0} -quiet] -quiet
