# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ryanp/Documents/Grad-School/ECE-540-SoC-Progammable-Logic-FPGAs/Projects/proj2-rojobot-new/proj2-rojobot-new/project_1/project_1.srcs/sources_1/ip/world_map_lr/world_map_lr.xci
# IP: The module: 'world_map_lr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryanp/Documents/Grad-School/ECE-540-SoC-Progammable-Logic-FPGAs/Projects/proj2-rojobot-new/proj2-rojobot-new/project_1/project_1.srcs/sources_1/ip/world_map_lr/world_map_lr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'world_map_lr'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ryanp/Documents/Grad-School/ECE-540-SoC-Progammable-Logic-FPGAs/Projects/proj2-rojobot-new/proj2-rojobot-new/project_1/project_1.srcs/sources_1/ip/world_map_lr/world_map_lr.xci
# IP: The module: 'world_map_lr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ryanp/Documents/Grad-School/ECE-540-SoC-Progammable-Logic-FPGAs/Projects/proj2-rojobot-new/proj2-rojobot-new/project_1/project_1.srcs/sources_1/ip/world_map_lr/world_map_lr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'world_map_lr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
