# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/rromano/Documents/GitHub/Nexys-A7-Sidescroller-Game/project_1/project_1.srcs/sources_1/ip/world_map_loop/world_map_loop.xci
# IP: The module: 'world_map_loop' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rromano/Documents/GitHub/Nexys-A7-Sidescroller-Game/project_1/project_1.srcs/sources_1/ip/world_map_loop/world_map_loop_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'world_map_loop'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/rromano/Documents/GitHub/Nexys-A7-Sidescroller-Game/project_1/project_1.srcs/sources_1/ip/world_map_loop/world_map_loop.xci
# IP: The module: 'world_map_loop' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rromano/Documents/GitHub/Nexys-A7-Sidescroller-Game/project_1/project_1.srcs/sources_1/ip/world_map_loop/world_map_loop_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'world_map_loop'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
